inherit_from: .rubocop_todo.yml

Lint/ScriptPermission:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
Style/MethodCallWithoutArgsParentheses:
  Enabled: false

AllCops:
  NewCops: enable
